### ISSUE TITLE
Deconfuse wikis in github

### ISSUE THREAD

**Issue by rvs** [aifoundry-org/.github#3]
So here's the deal team: when I was setting up organization I got the impression that https://github.com/aifoundry-org/.github repo is expected to host not only the organizational README.md file (which gets displayed when you navigate to https://github.com/aifoundry-org) but also will host a wiki that will show up at the organization level. Obviously it doesn't seem to work that way. So... in order to not confuse everyone perhaps we should standardize on https://github.com/aifoundry-org/wiki as the place to host the wiki as well (and we can link to it in the organization-level README.md -- that's fine).

The only other concern that I have is when to use actual wiki vs. using .md files in the wiki repo. Let's start this discussion here and conclude it when we all get together on discord. Please summarize your pros/cons of .md files in repo vs. proper wiki articles like https://github.com/aifoundry-org/.github/wiki in the comments of this task.

**Comment by janchk** [comment]
Wiki for wiki seems fine. Then it would be easy to link that wiki in organization README file.

**Comment by Sadosh42** [comment]
I would say that in my experience navigating and using wiki here https://github.com/aifoundry-org/wiki is more intuitive to me, so I'd keep it here.

**Comment by deitch** [comment]
One advantage of the wiki repo is that it _is_ a repo, so pull requests and comments and such work. The flow can be helpful to us.
